services:
  postgres:
    image: postgres:17
    container_name: showsync-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - showsync-pgdata:/var/lib/postgresql/data

volumes:
  showsync-pgdata:
